local: &local 
  adapter: postgresql
  username: katya
  password: rubytest
  host: localhost

development: 
  <<: *local 
  database: tm_dev

test: 
  <<: *local 
  database: tm_test

production: 
  <<: *local 
  database: tm_production
